// Copyright 2024 Hypermode Inc.
// Licensed under the terms of the Apache License, Version 2.0
// See the LICENSE file that accompanied this code for further details.
//
// SPDX-FileCopyrightText: 2024 Hypermode Inc. <hello@hypermode.com>
// SPDX-License-Identifier: Apache-2.0

///|
fn host_add(_a : Int, _b : Int) -> Int {
  abort("should not be called")
}

///|
fn host_echo1(_message : String?) -> String? {
  abort("should not be called")
}

///|
fn host_echo2(_message : String?) -> String? {
  abort("should not be called")
}

///|
fn host_echo3(_message : String?) -> String? {
  abort("should not be called")
}

///|
fn host_echo4(_message : String?) -> String? {
  abort("should not be called")
}

///|
fn host_encode_strings1(_items : Array[String]?) -> String? {
  abort("should not be called")
}

///|
fn host_encode_strings2(_items : Array[String?]?) -> String? {
  abort("should not be called")
}
