// Copyright 2024 Hypermode Inc.
// Licensed under the terms of the Apache License, Version 2.0
// See the LICENSE file that accompanied this code for further details.
//
// SPDX-FileCopyrightText: 2024 Hypermode Inc. <hello@hypermode.com>
// SPDX-License-Identifier: Apache-2.0

///|
pub fn host_add(a : Int, b : Int) -> Int {
  abort("should not be called")
}

///|
pub fn host_echo1(message : String?) -> String? {
  abort("should not be called")
}

///|
pub fn host_echo2(message : String?) -> String? {
  abort("should not be called")
}

///|
pub fn host_echo3(message : String?) -> String? {
  abort("should not be called")
}

///|
pub fn host_echo4(message : String?) -> String? {
  abort("should not be called")
}

///|
pub fn host_encode_strings1(items : Array[String]?) -> String? {
  abort("should not be called")
}

///|
pub fn host_encode_strings2(items : Array[String?]?) -> String? {
  abort("should not be called")
}
