package modus:graphql

// GraphQL client interface
interface client {
    // Execute a GraphQL query with variables
    execute-query: func(
        host-name: string,
        statement: string,
        variables: string
    ) -> option<string>
}

world graphql-world {
    import client
}
