// HTTP client interface
interface http-client {
    // Headers type representation
    record headers {
        data: list<tuple<string, string>>
    }

    // HTTP Request record
    record request {
        url: string,
        method: string,
        headers: option<headers>,
        body: list<u8>
    }

    // HTTP Response record
    record response {
        status: u16,
        status-text: string,
        headers: option<headers>,
        body: list<u8>
    }

    // Fetch performs an HTTP request and returns a response
    fetch: func(request: request) -> option<response>;
}
