// Defines interface for random number generation for use with wazero.
interface random {
    // Read random bytes into the provided buffer
    // Returns number of bytes read
    read: func(buf: list<u8>) -> result<u32, string>
}
