/*
 * Copyright 2024 Hypermode Inc.
 * Licensed under the terms of the Apache License, Version 2.0
 * See the LICENSE file that accompanied this code for further details.
 *
 * SPDX-FileCopyrightText: 2024 Hypermode Inc. <hello@hypermode.com>
 * SPDX-License-Identifier: Apache-2.0
 */

package codegen

import (
	"bytes"
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/gmlewis/modus/sdk/go/tools/modus-moonbit-build/config"
	"github.com/gmlewis/modus/sdk/go/tools/modus-moonbit-build/metadata"
	"github.com/gmlewis/modus/sdk/go/tools/modus-moonbit-build/utils"
)

const post_file = "modus_post_generated.mbt"

func PostProcess(config *config.Config, meta *metadata.Metadata) error {
	body, header := testablePostProcess(meta)

	return writeBuffersToFile(filepath.Join(config.SourceDir, post_file), header, body)
}

func testablePostProcess(meta *metadata.Metadata) (body, header *bytes.Buffer) {
	imports := meta.GetImports()
	types := getTypes(meta)

	keys, pairs := genMapKeyValuePairs(meta)

	body = &bytes.Buffer{}
	writeFuncUnpin(body)
	writeFuncNew(body, types, imports)
	writeFuncMake(body, types, imports)
	// if len(keys) > 0 {
	writeFuncReadMap(body, keys, pairs)
	writeFuncWriteMap(body, keys, pairs)
	// }

	header = &bytes.Buffer{}
	writePostProcessHeader(header, meta, imports)

	return body, header
}

func getTypes(meta *metadata.Metadata) []*metadata.TypeDefinition {
	types := utils.MapValues(meta.Types)
	sort.Slice(types, func(i, j int) bool {
		return types[i].Id < types[j].Id
	})
	return types
}

const postProcessHeader = `// Code generated by modus-moonbit-build. DO NOT EDIT.

// Copied from: https://github.com/peter-jerry-ye/wit-bindgen/blob/266edc9a0d08b60a7d076f81905768f70d657953/crates/moonbit/src/lib.rs#L28-L194

pub extern "wasm" fn extend16(value : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.extend16_s)

pub extern "wasm" fn extend8(value : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.extend8_s)

pub extern "wasm" fn store8(offset : Int, value : Int) =
  #|(func (param i32) (param i32) local.get 0 local.get 1 i32.store8)

pub extern "wasm" fn load8_u(offset : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.load8_u)

pub extern "wasm" fn load8(offset : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.load8_s)

pub extern "wasm" fn store16(offset : Int, value : Int) =
  #|(func (param i32) (param i32) local.get 0 local.get 1 i32.store16)

pub extern "wasm" fn load16(offset : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.load16_s)

pub extern "wasm" fn load16_u(offset : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.load16_u)

pub extern "wasm" fn store32(offset : Int, value : Int) =
  #|(func (param i32) (param i32) local.get 0 local.get 1 i32.store)

pub extern "wasm" fn load32(offset : Int) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.load)

pub extern "wasm" fn store64(offset : Int, value : Int64) =
  #|(func (param i32) (param i64) local.get 0 local.get 1 i64.store)

pub extern "wasm" fn load64(offset : Int) -> Int64 =
  #|(func (param i32) (result i64) local.get 0 i64.load)

pub extern "wasm" fn storef32(offset : Int, value : Float) =
  #|(func (param i32) (param f32) local.get 0 local.get 1 f32.store)

pub extern "wasm" fn loadf32(offset : Int) -> Float =
  #|(func (param i32) (result f32) local.get 0 f32.load)

pub extern "wasm" fn storef64(offset : Int, value : Double) =
  #|(func (param i32) (param f64) local.get 0 local.get 1 f64.store)

pub extern "wasm" fn loadf64(offset : Int) -> Double =
  #|(func (param i32) (result f64) local.get 0 f64.load)

pub extern "wasm" fn f32_to_i32(value : Float) -> Int =
  #|(func (param f32) (result i32) local.get 0 f32.convert_i32_s)

pub extern "wasm" fn f32_to_i64(value : Float) -> Int64 =
  #|(func (param f32) (result i64) local.get 0 f32.convert_i64_s)

// set pseudo header; allocate extra bytes for string
pub extern "wasm" fn malloc(size : Int) -> Int =
  #|(func (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 4 i32.add call $moonbit.gc.malloc
  #| local.tee 1 i32.const 0 call $moonbit.init_array8
  #| local.get 1 i32.const 8 i32.add)

pub extern "wasm" fn free(position : Int) =
  #|(func (param i32) local.get 0 i32.const 8 i32.sub call $moonbit.decref)

extern "wasm" fn copy(dest : Int, src : Int, len : Int) =
  #|(func (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 memory.copy)

pub extern "wasm" fn str2ptr(str : String) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn ptr2str(ptr : Int, len : Int) -> String =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array16
  #| local.get 2)

pub extern "wasm" fn bytes2ptr(bytes : FixedArray[Byte]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn ptr2bytes(ptr : Int, len : Int) -> FixedArray[Byte] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array8
  #| local.get 2)

pub extern "wasm" fn uint_array2ptr(array : FixedArray[UInt]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn uint64_array2ptr(array : FixedArray[UInt64]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn int_array2ptr(array : FixedArray[Int]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn int64_array2ptr(array : FixedArray[Int64]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn float_array2ptr(array : FixedArray[Float]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn double_array2ptr(array : FixedArray[Double]) -> Int =
  #|(func (param i32) (result i32) local.get 0 i32.const 8 i32.add)

pub extern "wasm" fn ptr2uint_array(ptr : Int, len : Int) -> FixedArray[UInt] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array32
  #| local.get 2)

pub extern "wasm" fn ptr2int_array(ptr : Int, len : Int) -> FixedArray[Int] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array32
  #| local.get 2)

pub extern "wasm" fn ptr2float_array(ptr : Int, len : Int) -> FixedArray[Float] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array32
  #| local.get 2)

pub extern "wasm" fn ptr2uint64_array(ptr : Int, len : Int) -> FixedArray[UInt64] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array64
  #| local.get 2)

pub extern "wasm" fn ptr2int64_array(ptr : Int, len : Int) -> FixedArray[Int64] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array64
  #| local.get 2)

pub extern "wasm" fn ptr2double_array(ptr : Int, len : Int) -> FixedArray[Double] =
  #|(func (param i32) (param i32) (result i32) (local i32)
  #| local.get 0 i32.const 8 i32.sub local.tee 2
  #| local.get 1 call $moonbit.init_array64
  #| local.get 2)

pub fn cabi_realloc(
    src_offset : Int,
    src_size : Int,
    _dst_alignment : Int,
    dst_size : Int
) -> Int {{
    // malloc
    if src_offset == 0 && src_size == 0 {{
        return malloc(dst_size)
    }}
    // free
    if dst_size == 0 {{
        free(src_offset)
        return 0
    }}
    // realloc
    let dst = malloc(dst_size)
    copy(dst, src_offset, if src_size < dst_size { src_size } else { dst_size })
    free(src_offset)
    dst
}}

pub(open) trait Any {}
pub(all) struct Cleanup {
    address : Int
    size : Int
    align : Int
}

///|
pub fn ptr_to_none() -> Int {
  let val : Double? = None
  cast(val)
}

///|
fn cast[A, B](a : A) -> B = "%identity"

///|
pub fn moonbit_bytes_to_array(ptr : Int) -> Int {
  let bytes : Bytes = cast(ptr)
  let result = bytes.to_array()
  cast(result)
}

///|
pub fn moonbit_bytes_make(size : Int, val : Int) -> Int =
  #|(func (param i32) (param i32) (result i32) local.get 0 local.get 1 call $moonbit.bytes_make)

///|
pub fn moonbit_float32_array_make(size : Int, val : Float) -> Int =
  #|(func (param i32) (param f32) (result i32) local.get 0 local.get 1 call $moonbit.float32_array_make)

///|
pub fn moonbit_float_array_make(size : Int, val : Double) -> Int =
  #|(func (param i32) (param f64) (result i32) local.get 0 local.get 1 call $moonbit.float_array_make)

///|
pub fn moonbit_i32_array_make(size : Int, val : Int) -> Int =
  #|(func (param i32) (param i32) (result i32) local.get 0 local.get 1 call $moonbit.i32_array_make)

///|
pub fn moonbit_int16_array_make(size : Int, val : Int) -> Int =
  #|(func (param i32) (param i32) (result i32) local.get 0 local.get 1 call $moonbit.int16_array_make)

///|
pub fn moonbit_int64_array_make(size : Int, val : Int64) -> Int =
  #|(func (param i32) (param i64) (result i32) local.get 0 local.get 1 call $moonbit.int64_array_make)

///|
pub fn moonbit_ref_array_make(size : Int, val : Int) -> Int =
  #|(func (param i32) (param i32) (result i32) local.get 0 local.get 1 call $moonbit.ref_array_make)
`

func writePostProcessHeader(b *bytes.Buffer, meta *metadata.Metadata, imports map[string]string) {
	b.WriteString(postProcessHeader)

	if _, ok := imports["@time"]; ok {
		b.WriteString(`
///|
pub fn zoned_date_time_from_unix_seconds_and_nanos(second : Int64, nanos : Int64) -> @time.ZonedDateTime raise Error {
  let nanosecond = (nanos % 1_000_000_000).to_int()
  @time.unix!(second, nanosecond~)
}

///|
pub fn duration_from_nanos(nanoseconds : Int64) -> @time.Duration raise Error {
  @time.Duration::of!(nanoseconds~)
}
`)
	}
}

func writeFuncUnpin(b *bytes.Buffer) {
	// b.WriteString(`
	// var __pins = make(map[unsafe.Pointer]int)
	//
	// //go:export __unpin
	// func __unpin(p unsafe.Pointer) {
	// 	n := __pins[p]
	// 	if n == 1 {
	// 		delete(__pins, p)
	// 	} else {
	// 		__pins[p] = n - 1
	// 	}
	// }`)
	//
	// 	b.WriteString("\n")
}

func writeFuncNew(b *bytes.Buffer, types []*metadata.TypeDefinition, imports map[string]string) {
	// 	buf := &bytes.Buffer{}
	// 	found := false
	//
	// 	buf.WriteString(`
	// //go:export __new
	// func __new(id int) unsafe.Pointer {
	// `)
	// 	buf.WriteString("\tswitch id {\n")
	// 	for _, t := range types {
	// 		if utils.IsSliceType(t.Name) && utils.IsMapType(t.Name) {
	// 			continue
	// 		}
	//
	// 		ptrName := utils.GetNameForType(t.Name, imports)
	// 		elementName := utils.GetUnderlyingType(ptrName)
	// 		found = true
	// 		buf.WriteString(fmt.Sprintf(`	case %d:
	// 		o := new(%s)
	// 		p := unsafe.Pointer(o)
	// 		__pins[p]++
	// 		return p
	// `, t.Id, elementName))
	// 	}
	// 	buf.WriteString("\t}\n\n")
	// 	buf.WriteString("\treturn nil\n}\n")
	//
	// 	if found {
	// 		_, _ = buf.WriteTo(b)
	// 	}
}

func writeFuncMake(b *bytes.Buffer, types []*metadata.TypeDefinition, imports map[string]string) {
	// b.WriteString(`
	// //go:export __make
	// func __make(id, size int) unsafe.Pointer {
	// 	switch id {
	// 	case 1:
	// 		o := make([]byte, size)
	// 		p := unsafe.Pointer(&o)
	// 		__pins[p]++
	// 		return p
	// 	case 2:
	// 		o := string(make([]byte, size))
	// 		p := unsafe.Pointer(&o)
	// 		__pins[p]++
	// 		return p
	// `)
	//
	// 	for _, t := range types {
	// 		name := utils.GetNameForType(t.Name, imports)
	// 		if utils.IsSliceType(name) || utils.IsMapType(name) {
	// 			b.WriteString(fmt.Sprintf(`	case %d:
	// 		o := make(%s, size)
	// 		p := unsafe.Pointer(&o)
	// 		__pins[p]++
	// 		return p
	// `, t.Id, name))
	// 		}
	// 	}
	//
	// 	b.WriteString("\t}\n\n")
	// 	b.WriteString("\treturn nil\n}\n")
}

func writeFuncReadMap(b *bytes.Buffer, keys []string, pairs pairsMapT) {
	buf := &bytes.Buffer{}
	buf.WriteString(`
///|
pub fn read_map(key_type_name_ptr : Int, value_type_name_ptr : Int, map_ptr : Int) -> Int64 {
  let key_type_name : String = cast(key_type_name_ptr)
  let value_type_name : String = cast(value_type_name_ptr)
  match (key_type_name, value_type_name) {
`)

	patterns, helpers := genReadMapPatternsAndHelpers(keys, pairs)
	buf.WriteString(patterns)
	buf.WriteString(`
  }
}
`)
	buf.WriteString(helpers)

	if helpers != "" {
		_, _ = buf.WriteTo(b)
	}
}

func genReadMapPatternsAndHelpers(keys []string, pairs pairsMapT) (string, string) {
	var patterns []string
	var helpers []string
	for _, kvPair := range keys {
		keyTypeName := pairs[kvPair].keyTypeName
		valueTypeName := pairs[kvPair].valueTypeName
		patterns = append(patterns, fmt.Sprintf("    (%q, %q) => read_map_helper_%v(map_ptr)", keyTypeName, valueTypeName, len(helpers)))
		helpers = append(helpers, genReadMapHelperFuncs(len(helpers), keyTypeName, valueTypeName))
	}

	patterns = append(patterns, "    _ => 0")
	return strings.Join(patterns, "\n"), strings.Join(helpers, "\n")
}

func genReadMapHelperFuncs(fnNum int, keyTypeName, valueTypeName string) string {
	return fmt.Sprintf(`///|
fn read_map_helper_%v(map_ptr : Int) -> Int64 {
  let m : Map[%v, %v] = cast(map_ptr)
  let pairs = m.to_array()
  let keys = pairs.map(fn(t) { t.0 })
  let values = pairs.map(fn(t) { t.1 })
  let keys_ptr : Int = cast(keys)
  let values_ptr : Int = cast(values)
  (keys_ptr.to_int64() << 32) | values_ptr.to_int64()
}
`, fnNum, keyTypeName, valueTypeName)
}

func writeFuncWriteMap(b *bytes.Buffer, keys []string, pairs pairsMapT) {
	buf := &bytes.Buffer{}
	buf.WriteString(`
///|
pub fn write_map(
  key_type_name_ptr : Int,
  value_type_name_ptr : Int,
  keys_ptr : Int,
  values_ptr : Int
) -> Int {
  let key_type_name : String = cast(key_type_name_ptr)
  let value_type_name : String = cast(value_type_name_ptr)
  match (key_type_name, value_type_name) {
`)

	patterns, helpers := genWriteMapPatternsAndHelpers(keys, pairs)
	buf.WriteString(patterns)
	buf.WriteString(`
  }
}
`)
	buf.WriteString(helpers)

	if helpers != "" {
		_, _ = buf.WriteTo(b)
	}
}

func genWriteMapPatternsAndHelpers(keys []string, pairs pairsMapT) (string, string) {
	var patterns []string
	var helpers []string
	for _, kvPair := range keys {
		keyTypeName := pairs[kvPair].keyTypeName
		valueTypeName := pairs[kvPair].valueTypeName
		patterns = append(patterns, fmt.Sprintf("    (%q, %q) => write_map_helper_%v(keys_ptr, values_ptr)", keyTypeName, valueTypeName, len(helpers)))
		helpers = append(helpers, genWriteMapHelperFuncs(len(helpers), keyTypeName, valueTypeName))
	}

	patterns = append(patterns, "    _ => 0")
	return strings.Join(patterns, "\n"), strings.Join(helpers, "\n")
}

func genWriteMapHelperFuncs(fnNum int, keyTypeName, valueTypeName string) string {
	return fmt.Sprintf(`///|
fn write_map_helper_%v(keys_ptr: Int, values_ptr: Int) -> Int {
  let keys : Array[%[2]v] = cast(keys_ptr)
  let values : Array[%[3]v] = cast(values_ptr)
  let m : Map[%[2]v, %[3]v] = Map::new(capacity=keys.length())
  for i in 0..<keys.length() {
    m[keys[i]] = values[i]
  }
  cast(m)
}
`, fnNum, keyTypeName, valueTypeName)
}

type keyValuePair struct {
	keyTypeName   string
	valueTypeName string
}

type pairsMapT map[string]*keyValuePair

func genMapKeyValuePairs(meta *metadata.Metadata) (keys []string, pairs pairsMapT) {
	pairs = map[string]*keyValuePair{}

	for typ := range meta.Types {
		if utils.IsMapType(typ) {
			keyTypeName, valueTypeName := utils.GetMapSubtypes(typ)
			mapTypeName := fmt.Sprintf("Map[%v, %v]", keyTypeName, valueTypeName)
			if _, ok := pairs[mapTypeName]; ok {
				continue
			}
			pairs[mapTypeName] = &keyValuePair{keyTypeName: keyTypeName, valueTypeName: valueTypeName}
		}
	}

	// Output the patterns and helpers in sorted order.
	keys = slices.Sorted(maps.Keys(pairs))

	return keys, pairs
}
