// -*- compile-command: "go test -run ^TestTestablePreProcess_Neo4j ."; -*-

/*
 * Copyright 2024 Hypermode Inc.
 * Licensed under the terms of the Apache License, Version 2.0
 * See the LICENSE file that accompanied this code for further details.
 *
 * SPDX-FileCopyrightText: 2024 Hypermode Inc. <hello@hypermode.com>
 * SPDX-License-Identifier: Apache-2.0
 */

package codegen

import (
	"testing"

	"github.com/gmlewis/modus/sdk/go/tools/modus-moonbit-build/config"
)

func TestTestablePreProcess_Neo4j(t *testing.T) {
	t.Parallel()

	config := &config.Config{
		SourceDir: "../testdata/neo4j-example",
	}

	mod := preProcessTestSetup(t, config)

	body, header, moonPkgJSON, err := testablePreProcess(config, mod)
	if err != nil {
		t.Fatal(err)
	}

	wg := &preProcessDiffs{
		wantPreProcessBody:        wantNeo4jPreProcessBody,
		gotPreProcessBody:         body.String(),
		wantPreProcessHeader:      wantNeo4jPreProcessHeader,
		gotPreProcessHeader:       header.String(),
		wantPreProcessMoonPkgJSON: wantNeo4jPreProcessMoonPkgJSON,
		gotPreProcessMoonPkgJSON:  moonPkgJSON.String(),
	}
	reportPreProcessDiffs(t, "neo4j", wg)
}

var wantNeo4jPreProcessBody = `pub fn __modus_create_people_and_relationships() -> String!Error {
  try create_people_and_relationships!() {
    e => {
      @console.error(e.to_string())
      raise e
    }
  }
}

pub fn __modus_get_alice_friends_under_40() -> Array[Person]!Error {
  try get_alice_friends_under_40!() {
    e => {
      @console.error(e.to_string())
      raise e
    }
  }
}

pub fn __modus_get_alice_friends_under_40_ages() -> Array[Int]!Error {
  try get_alice_friends_under_40_ages!() {
    e => {
      @console.error(e.to_string())
      raise e
    }
  }
}

pub fn __modus_delete_all_nodes() -> String!Error {
  try delete_all_nodes!() {
    e => {
      @console.error(e.to_string())
      raise e
    }
  }
}

`

var wantNeo4jPreProcessHeader = `// Code generated by modus-moonbit-build. DO NOT EDIT.

`

var wantNeo4jPreProcessMoonPkgJSON = `{
  "import": [
    "gmlewis/modus/pkg/neo4j",
    "gmlewis/modus/pkg/console"
  ],
  "targets": {
    "modus_post_generated.mbt": [
      "wasm"
    ]
  },
  "link": {
    "wasm": {
      "exports": [
        "__modus_create_people_and_relationships:create_people_and_relationships",
        "__modus_delete_all_nodes:delete_all_nodes",
        "__modus_get_alice_friends_under_40:get_alice_friends_under_40",
        "__modus_get_alice_friends_under_40_ages:get_alice_friends_under_40_ages",
        "cabi_realloc",
        "copy",
        "free",
        "load32",
        "malloc",
        "ptr2str",
        "ptr_to_none",
        "read_map",
        "store32",
        "store8",
        "write_map"
      ],
      "export-memory-name": "memory"
    }
  }
}`
