///|
pub fn hello_tuples_2_strings() -> (String, String) {
  ("banana", "cherry")
}

///|
pub fn hello_tuples_3_strings() -> (String, String, String) {
  ("date", "elderberry", "fig")
}

///|
pub fn hello_tuples_4_strings() -> (String, String, String, String) {
  ("grape", "honeydew", "imbe", "jackfruit")
}

///|
pub fn hello_tuples_5_strings() -> (String, String, String, String, String) {
  ("kiwi", "lemon", "mango", "nectarine", "orange")
}

///|
pub fn hello_tuples_6_strings() -> (
  String,
  String,
  String,
  String,
  String,
  String,
) {
  ("papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli")
}

///|
pub fn hack() -> Array[String] {
  ["d", "e", "f"]
}
